name: CPP project with catch2 CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      CC: clang
      CXX: clang++

    steps:
      - name: Setup dependencies
        run: |
          sudo apt-get install -y clang-tidy

      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check for bad words
        run: "! grep -R --exclude-dir=etc -n -w -f .bad_words src libs"
      - name: Run clang format
        run: "find . -iname *.h -o -iname *.hpp -o -iname *.cpp -exec clang-format --dry-run --Werror -style=file {} +"

      - name: Build default
        run: |
          mkdir build
          cmake -S. -Bbuild -DUSE_CLANG_TIDY=TRUE -DTESTS_BUILD_TYPE=NONE -DCMAKE_BUILD_TYPE=Release
          cmake --build build

      - name: Upload hw2 tests
        uses: actions/upload-artifact@v4
        with:
          name: ExponentialTests
          path: ./build/test/ExponentialTests

      - name: Upload hw3 tests
        uses: actions/upload-artifact@v4
        with:
          name: ExpressionTests
          path: ./build/test/ExpressionTests

  hw2-tests:
    needs: build
    runs-on: ubuntu-22.04

    steps:
      - name: Download tests
        uses: actions/download-artifact@v4
        with:
          name: ExponentialTests


      - name: Run tests
        timeout-minutes: 10
        run: |
          chmod +x ./ExponentialTests
          ./ExponentialTests

  hw3-tests:
    needs: hw2-tests

    runs-on: ubuntu-22.04

    steps:
      - name: Download tests
        uses: actions/download-artifact@v4
        with:
          name: ExpressionTests

      - name: Run tests
        timeout-minutes: 10
        run: |
          chmod +x ./ExpressionTests
          ./ExpressionTests
