name: CPP project with catch2 CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      CC: clang
      CXX: clang++

    steps:
      - name: Setup dependencies
        run: |
          sudo apt-get install -y clang-tidy

      - name: Checkout repository with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check for bad words
        run: "! grep -R --exclude-dir=etc -n -w -f .bad_words src libs"

      - name: Run clang format
        run: "find . -iname *.h -o -iname *.hpp -o -iname *.cpp -exec clang-format --dry-run --Werror -style=file {} +"

      - name: Configure Cmake
        run: |
          mkdir build
          cmake -S. -Bbuild -DUSE_CLANG_TIDY=TRUE -DTESTS_BUILD_TYPE=NONE -DCMAKE_BUILD_TYPE=Release

      - name: Build hw2 tests
        run:
          cmake --build build --target ExponentialTests

      - name: Run hw2 tests
        run: |
          chmod +x ./build/test/ExponentialTests
          ./build/test/ExponentialTests

      - name: Build hw3 tests
        run:
          cmake --build build --target ExpressionTests

      - name: Run hw3 tests
        run: |
          chmod +x ./build/test/ExpressionTests
          ./build/test/ExpressionTests